version: '2.4'
services:
  
  smokeping:
    image: lscr.io/linuxserver/smokeping
    container_name: smokeping
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Berlin
    volumes:
      - ./smokeping/config:/config
      - ./smokeping/data:/data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.smokeping.rule=Host(`smokeping.internal.4o4-app.eu`)"
      - "traefik.http.services.smokeping.loadbalancer.server.port=80"
      - "traefik.http.routers.smokeping.entrypoints=web-secure"
      - "traefik.http.routers.smokeping.tls.certResolver=primary"
    networks:
      macvlan_network:
        ipv4_address: 192.168.2.243

networks:
  macvlan_network:
    external: true
