version: '3'
services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    # hostname: example.com # set to fqdn of host
    ports:
      - 19999:19999
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    environment:
      TZ: Europe/Berlin
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.netdata.rule=Host(`netdata.internal.4o4-app.eu`)"
      - "traefik.http.services.netdata.loadbalancer.server.port=19999"
      - "traefik.http.routers.netdata.entrypoints=web-secure"
      - "traefik.http.routers.netdata.tls.certResolver=primary"
    networks:
      macvlan_network:
        ipv4_address: 192.168.2.244
        
volumes:
  netdataconfig:
  netdatalib:
  netdatacache:

networks:
  macvlan_network:
    external: true
